name: Fuzzing

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  contents: read

jobs:
  python-fuzzing:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
    - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
      with:
        python-version: "3.11"
    - name: Install atheris
      run: pip install atheris
    - name: Run Python Fuzzing
      run: python fuzz_test.py -atheris_runs=10000
      working-directory: dependatool
      timeout-minutes: 2

  rust-fuzzing:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
    - name: Install cargo-fuzz
      run: cargo install cargo-fuzz
    - name: Run Rust Fuzzing
      run: cargo fuzz run fuzz_target_1 -- -max_total_time=10
      working-directory: rust/core
      timeout-minutes: 2
